---
- hosts: all
  vars:
  
  tasks:
    
  - name: Echo hostname
    shell: echo {{ansible_host}} 

  - name: Reboot
    shell: sleep 5 && reboot
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for play hosts to be up again
    wait_for_connection:
      connect_timeout: 60
      sleep: 5
      delay: 5
      timeout: 300
  
  - name:
    shell: uptime
