---
- hosts: all
  vars:
  
  tasks:
    
  - name: Echo hostname
    shell: echo {{ansible_host}} 

  - name: Reboot
    shell: sleep 2 && reboot
    async: 30
    poll: 0
    ignore_errors: true

  - name: Wait for play hosts to be up again
    wait_for:
      host: '{{hostvars[item].ansible_host}}'
      port: 22
      state: started
      delay: 10
      timeout: 45
    with_items: '{{play_hosts}}' 
    connection: local
  
  - name:
    shell: uptime
